config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions' }
  devise_scope :user do
    post "/users/guest_sign_in" => "users/sessions#new_guest"
  end
  root to: 'homes#top'
  get "home/welcome" => "homes#welcome"
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update index]
  resources :matches, only: %i[index update destroy create edit]
  resources :contacts, only: [:create]
  resources :messages, only: %i[create destroy]
  resources :rooms, only: %i[create show]
  resource :contacts, only: %i[new create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, :trackable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :matches, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :email, presence: true
  validates :country, inclusion: { in: [true, false] }
  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }, on: :create

  def like_sum
    sum = 0
    posts.each do |post|
      sum += post.likes.count
    end
    sum
  end

  def self.guest
    find_or_create_by(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "GUEST"
      user.country = false
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    home_welcome_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    home_welcome_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  # def after_sign_in_path_for(resource)
  #   case resource
  #   when User
  #     posts_path
  #   when AdminUser
  #     stored_location_for(resource) ||
  #       if resource.is_a?(AdminUser)
  #         root_path
  #       else
  #         super
  #       end
  #   end
  # end

  def new_guest
    # ゲストユーザーがあれば取り出す、なければ新規作成する
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: "You logged in as a GUEST USER"
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  include EnsureCorrectUser
  before_action :ensure_correct_user, only: %i[edit update]

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).recent.page(params[:page]).per(4)
    @matches = Match.includes(:user).where(user_id: @user.id).recent.page(params[:page]).per(4)
    @room = current_user.rooms.find_by(guest_id: @user.id)
    @room ||= @user.rooms.find_by(guest_id: current_user.id)
    # 通知
    @notifications = current_user.passive_notifications.page(params[:page]).per(4)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def index
    @users = User.includes(:posts).page(params[:page]).per(8).order(current_sign_in_at: 'DESC')
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'User has been updated'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:profile, :image, :name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="body">
  <div class="container">
	<!---------------------- パンくずリスト -------------------------->
	<div class="row">
	  <div class="col-xs-6">
	    <ol class="breadcrumb">
		  <li><%= link_to "Home", posts_path, data: { "turbolinks" => false }, class: "glyphicon glyphicon-home"%></li>
		  <li><%= link_to "My page", user_path(@user) %></li>
		  <li class="active">User Edit</li>
		</ol>
	  </div>
	</div>
	<!------------------------------------------------------------->
  <!-------------------- プロフィール --------------------------->
		<%= render "shared/simple_profile" %>
	<!-------------------------------------------------------->
	<!-------------------     エラーメッセージ  -------------->
		<%= render "shared/error_messages", model: @user %>
	<!--------------------------------------------------------->
		<div class="margin-container row">
		  <div class="edit-user col-xs-offset-2 col-xs-8">
			<h2 class="edit-title">- <%= fa_icon "cog" %>  Edit User -</h2>
			<div class="box-simple">
			  <%= form_with model: @user, local: true do |f| %>
			  <div class="row">
			    <div class="user-edit-image">
				  <%= attachment_image_tag @user, :image, fallback: "no-image.jpg", class: "user-image user-preview", id: "user-edit-image-size"%>
				</div>
			  </div>
			  <div class="row">
			    <div class="image-field col-xs-offset-2">
				  <%= f.attachment_field :image, id: "edit-user-image" %>
				</div>
			  </div>
			　<div class="row">
				<div class="col-xs-offset-1 col-xs-4">
				  <div class="name_field">
				    <%= f.label "Name" , class: "contorol-label" %><br >
					<%= f.text_field :name, class: "form-control" %>
				  </div>
				</div>
				<div class="col-xs-offset-1 col-xs-10">
				　　<div class="form-group profile-field">
				  　　<%= f.label "Profile" , class: "contorol-label" %><br >
				  　　<%= f.text_area :profile, class: "form-control", rows: "6" %>
				　　</div>
			 　　</div>
			　</div>
			　<div class="row">
			  　　<div class="update-btn col-xs-offset-9">
			    　　　<%= f.submit "Update", class: "btn btn-info" %>
			 　　 </div>
			　</div>
			　<% end %>
		  </div>
		</div>
      </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="body">
  <div class="container">
		<!-- --------------- パンくずリスト ---------------  -->
    <div class="row">
	  <div class="col-xs-3">
	    <ol class="breadcrumb">
		  <li><%= link_to "Home", posts_path, data: { "turbolinks" => false }, class: "glyphicon glyphicon-home" %></li>
		  <li class="active">Users</li>
		</ol>
	  </div>
	</div>
		<!-- ---------------------------------------------  -->
		<!----------------   プロフィール ---------------------->
	<%= render "shared/simple_profile" %>
		<!----------------------------------------------------->
	<div class="row">
	  <div class="col-xs-offset-2 col-xs-8">
	    <div class="title-wrapper">
		  <h2 class="users-title"><%= fa_icon "users" %>  All Users</h2>
		</div>
		<table class="table table-hover">
		  <thead>
	        <tr>
			  <th class="text-center"></th>
			  <th class="text-center">Name</th>
			  <th class="text-center">Country</th>
			  <th class="text-center">All Likes</th>
			  <th class="text-center">Last Login</th>
		    </tr>
		  </thead>
		  <tbody>
		    <% @users.each do |user| %>
		      <tr>
			    <td class="text-center" style="vertical-align: middle;">
				  <%= attachment_image_tag user, :image, fallback: "no-image.jpg", size:"60x60", id: "round-user-image" %>
				</td>
				<td class="text-center" style="vertical-align: middle;">
	        	  <%= link_to user_path(user) do %>
				    <%= user.name %>
				  <% end %>
				</td>
				<td class="text-center" style="vertical-align: middle;">
				  <% if user.country == true %>
					Philipins
				  <% else %>
					Japan
				  <% end %>
				</td>
				<td class="text-center" style="vertical-align: middle;">
				  <%= user.like_sum %>
				</td>
				<td class="text-center" style="vertical-align: middle;">
				  <%= user.current_sign_in_at.strftime("%Y-%m-%d %H:%M") %>
				</td>
			  </tr>
			<% end %>
			<%= paginate @users %>
		  </tbody>
		</table>
	  </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="body">
  <div class="container">
  <!--------------- パンくずリスト ------------------->
    <div class="row">
	  <div class="col-xs-4">
	    <ol class="breadcrumb">
		  <li><%= link_to "Home", posts_path, data: { "turbolinks" => false }, class: "glyphicon glyphicon-home" %></li>
		  <li class="active">My page</li>
	    </ol>
	  </div>
	</div>
  <!-------------------------------------------->
  <!----------  簡易プロフィール --------------------->
	<% unless current_user.id == @user.id %>
	  <%= render "shared/simple_profile" %>
    <% end %>
  <!------------------------------------------>
  <!------------- フラッシュメッセージ　-------->
	<%= render partial: "shared/flash" %>
  <!------------------------------------------>
  <!------------------ プロフィール　--------------->
	<div class="margin-container row">
	  <div class="col-xs-offset-2 col-xs-8">
	    <h2 class="profile-title">- <%= fa_icon "address-card-o" %> <%= @user.name %>`s Profile -</h2>
		<div class="box-simple">
		  <div class="row">
		    <div class="profile-image">
			  <%= attachment_image_tag @user, :image, fallback: "no-image.jpg", size:"300x300" %>
		    </div>
		  </div>
		 <!-------メッセージアイコン -------->
		  <div class="row">
		    <div class="col-xs-offset-10">
		      <% unless @user.id == current_user.id %>
			    <% if @room %>
			      <%= link_to room_path(@room) do %>
				    <%= fa_icon "envelope 3x" %>
				  <% end %>
				<% else %>
				  <%= link_to rooms_path(@roomId, room: { guest_id: @user.id }), method: :post do %>
				    <%= fa_icon "envelope-o 3x" %>
				  <% end %>
				<% end %>
			  <% end %>
			</div>
		  </div>
		<!--------------------------------->
		  <div class="row">
		    <div class="profile-item col-xs-offset-1 col-xs-10">
			  <strong class="profile-tag">　Name　</strong><br>
			  <div  class="profile-text">
				<strong><%= @user.name %></strong>
		      </div>
			</div>
		  </div>
		  <div class="row">
		    <div class="profile-item col-xs-offset-1 col-xs-10">
			  <strong class="profile-tag">　Country　</strong><br>
			  <% if @user.country == true %>
			    <div  class="profile-text">
				  <strong>Philipins</strong>
			    </div>
			  <% else %>
				<div  class="profile-text">
			      <strong class="profile-text">Japan</strong>
				</div>
			  <% end %>
		    </div>
		  </div>
		  <div class="row">
		    <div class="profile-item col-xs-offset-1 col-xs-10">
			  <strong class="profile-tag">　Profile　</strong><br>
			  <% if @user.profile.blank? %>
			    <div  class="profile-text">
				  <strong> no self-introduction </strong>
				</div>
			  <% else %>
				<div  class="profile-text">
				  <strong><%= @user.profile %></strong>
				</div>
			  <% end %>
			</div>
		  </div>
		  <div class="row">
		    <div class="profile-item col-xs-offset-9 col-xs-5">
			  <% if @user.id == current_user.id %>
		        <%= link_to "Edit" , edit_user_path(current_user), data: { "turbolinks" => false }, class: "btn btn-primary" %>
		      <% end %>
			</div>
		  </div>
		</div>
	  </div>
	</div>
	<!-------------- プロフィール　　ここまで -------------------------->
	<!------------------- 通知一覧 --------------------------------->
	<% if current_user.id == @user.id %>
	  <hr>
	    <div class="margin-container row">
		  <div class="col-xs-offset-3 col-xs-6">
		    <h2 class="notification-title">- <%= fa_icon "bell-o" %> Notifications -</h2>
			<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
			  <% if notifications.exists? %>
			    <% @notifications.each do |notification| %>
				  <%= render "shared/notifications", notification: notification %>
				<% end %>
				<div class="col-xs-offset-9">
				  <%= paginate notifications %>
				</div>
			  <% else %>
				<p class="no-notifications">No notifications</p>
			  <% end %>
			    <p class="confirm"><%= fa_icon "exclamation-triangle" %> Confirmed notifications will be automatically deleted in 24 hours</p>
		  </div>
		</div>
	<% end %>
	<!---------------------------------------------------------->
	<!------------------------------ 投稿一覧 ------------------->
	<hr>
	  <div class="margin-container　row">
	    <div class="col-xs-offset- col-xs-6">
		  <h3 class="post-title">- <%= fa_icon "clone" %> <%= @user.name %>`s All Posts -</h3>
		  <% @posts.each do |post| %>
		    <div class="box-simple">
			  <div>
			    <%= attachment_image_tag post, :image, id: "user-show-post-image" %>
			  </div>
		<!------------------- いいね(非同期通信)　---------------------------->
			  <div id="likes_buttons_<%= post.id %>" class= "user-show-like">
			    <%= render partial: "likes/like", locals: { post: post } %>
			  </div>
		<!------------------------------------------------------------->
			  <div class="row">
			    <div class="box-simple user-show-post-text col-xs-offset-1 col-xs-10">
		          <strong><%= post.text %></strong>
		        </div>
		      </div>
		      <div class="row">
			    <div class="col-xs-offset-6">
		          <%= fa_icon "calendar" %>
		            <%= create_time_with_country(current_user, post) %>
		        </div>
		      </div>
		      <div class="row">
		        <div class="post-more col-xs-offset-8 col-xs-1">
		          <%= link_to "more", post_path(post), class: "btn btn-info btn-xs" %>
		        </div>
		        <div class="user-show-edit-btn">
		          <% if post.user_id == current_user.id %>
		            <%= link_to "Edit" , edit_post_path(post), data: { "turbolinks" => false }, class: "btn btn-success btn-xs" %>
		          <% end %>
		        </div>
		      </div>
			</div>
          <% end %>
          <div class="col-xs-offset-4 col-xs-7">
            <%= paginate @posts %>
          </div>
		</div>
	  </div>
	<!-----------------  投稿一覧　ここまで ----------------------->
	<!--------------------- マッチング投稿一覧 --------------------->
	  <div class="margin-container row">
	    <div class="col-xs-offset-1 col-xs-5">
		  <h3 class="match-title">- <%= fa_icon "handshake-o" %> Recruit posts -</h3>
		  <% @matches.each do |match| %>
		    <div class="box-simple">
			  <% if match.blank? %>
			    <strong>There is no Recruite post</strong>
			  <% else %>
			  	<div class="user-show-match-occupation-tag">
			  	  <% if match.occupation == true %>
			        <%= fa_icon "users" %>
				      Search Students
			      <% else %>
				    <%= fa_icon "graduation-cap" %>
				    Search Teachers
			      <% end %>
			    </div>
				<div class="row">
				  <div class="col-xs-offset-2 col-xs-10">
				    <strong class="user-show-match-title"><%= match.title %></strong>
				  </div>
			    </div>
				<div class="row">
				  <div class="user-show-match-text col-xs-offset-1 col-xs-10">
				    <%= match.text %>
				  </div>
				</div>
				<div class="row">
				  <div class="col-xs-offset-7">
				    <%= fa_icon "calendar" %>
					<%= create_time_with_country(current_user, match) %>
				  </div>
				</div>
				<div class="row">
				  <div class="user-show-match-edit-btn col-xs-offset-9">
				    <% if match.user.id == current_user.id %>
					  <%= link_to "Edit", edit_match_path(match),class: "btn btn-success" %>
					<% end %>
				  </div>
				</div>
			  <% end %>
			</div>
		  <% end %>
	      <%= paginate @matches %>
		</div>
	  </div>
	  <!--------------------------------------------------------->
  </div>
</div>