config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions' }
  devise_scope :user do
    post "/users/guest_sign_in" => "users/sessions#new_guest"
  end
  root to: 'homes#top'
  get "home/welcome" => "homes#welcome"
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update index]
  resources :matches, only: %i[index update destroy create edit]
  resources :contacts, only: [:create]
  resources :messages, only: %i[create destroy]
  resources :rooms, only: %i[create show]
  resource :contacts, only: %i[new create]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :notifications, dependent: :destroy
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

  include Recent

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user

  validates :text, presence: true
  validates :title, presence: true
  validates :occupation, inclusion: { in: [true, false] }

  include Recent

end

app/models/message.rb
class Message < ApplicationRecord
  has_many :notifications, dependent: :destroy
  belongs_to :user
  belongs_to :room

  validates :message, presence: true

  include Recent

  def create_notification_message!(current_user, message_id, visited_id)
    notification = current_user.active_notifications.new(
      message_id: message_id,
      visited_id: visited_id,
      action: 'message'
    )
    notification.save if notification.valid?
  end
end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :message, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true

  include Recent

  def self.destroy_read_notifications
    notifications = Notification.where(checked: true)
    notifications.delete_all
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :notifications, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :image

  validates :text, presence: true
  validates :text, length: { maximum: 141 }

  include Recent

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def create_notification_like!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  belongs_to :user
  belongs_to :guest, class_name: 'User', foreign_key: 'guest_id', optional: true

  include Recent

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, :trackable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :matches, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :email, presence: true
  validates :country, inclusion: { in: [true, false] }
  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }, on: :create

  def like_sum
    sum = 0
    posts.each do |post|
      sum += post.likes.count
    end
    sum
  end

  def self.guest
    find_or_create_by(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "GUEST"
      user.country = false
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def welcome
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!
  include EnsureCorrectUser
  before_action :ensure_correct_match, only: %i[destroy edit update]

  def index
    @search = Match.ransack(params[:q])
    @matches = @search.result.includes(:user).page(params[:page]).per(5).recent
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    @match.user_id = current_user.id
    if @match.save
      flash[:success] = 'Newly posted'
      redirect_to matches_path
    else
      @search = Match.ransack(params[:q])
      @matches = @search.result.includes(:user).page(params[:page]).per(5).recent
      render :index
    end
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    if @match.update(match_params)
      flash[:success] = 'Post has been updated'
      redirect_to matches_path
    else
      render :edit
    end
  end

  def destroy
    match = Match.find(params[:id])
    match.destroy
    flash[:danger] = 'Post has been deleted'
    redirect_to matches_path
  end

  private

  def match_params
    params.require(:match).permit(:text, :title, :occupation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def create_time_with_country(user, model)
    created_at = user.country.present? ? (model.created_at - 1.hour) : model.created_at
    created_at.strftime('%Y-%m-%d %H:%M')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/matches/edit.html.erb
<div class="match">
  <div class="container">
	<!------------------  パンくずリスト  -------------------------->
	<div class="row">
		<div class="col-xs-5">
			<ol class="bread_crumb_recruit breadcrumb">
				<li><%= link_to "Home", posts_path, data: { "turbolinks" => false }, class: "glyphicon glyphicon-home" %></li>
				<li><%= link_to "Recruit", matches_path %></li>
				<li class="active">Edit Post</li>
			</ol>
		</div>
	</div>
	<!------------------------------------------------------------->
	<!--------------------- プロフィール --------------------------->
	<%= render "shared/simple_profile" %>
	<!------------------------------------------------------------>
	<!---------------------  エラーメッセージ ----------------------->
	<%= render "shared/error_messages", model: @match %>
	<!----------------------------------------------------------->
	<div class="margin-container row">
	  <div class="col-xs-offset-3 col-xs-6">
	    <h2 class="edit-title">- <%= fa_icon "cog" %>Edit Your Post -</h2>
		<div class="box-simple">
		  <%= form_with model: @match, local: true do |f| %>
		    <div class="row">
			  <div class="match-new-occupation col-xs-offset-2 col-xs-10">
			    <%= f.radio_button :occupation, :true, checked: true %>
			    <%= fa_icon "users" %>
			    <%= f.label :occupation, "Search Students　" %><br>
			    <%= f.radio_button :occupation, :false %>
			    <%= fa_icon "graduation-cap" %>
			    <%= f.label :occupation, "Search Teachers" %>
		      </div>
			</div>
			<div class="row">
			  <div class="col-xs-offset-1 col-xs-10">
			    <%= f.label :title, "Title" %><br />
			    <%= f.text_field :title, class: "form-control" %>
			    <%= f.label :text, "Text" %><br />
			    <%= f.text_area :text, class: "form-control", rows: "8", cols: "40" %>
		      </div>
			</div>
			<div class="row">
			  <div class="match-margin col-xs-offset-6">
				<%= f.submit "Update", class: "btn btn-primary"%>
				<%= link_to "Delete", match_path, method: :delete, data: { confirm: "Are you sure you want to delete it?", cancel: "No", commit: "Yes" },title: "Confirmation", class: "btn btn-danger" %>
			  </div>
			</div>
		  <% end %>
		</div>
	  </div>
	</div>
  </div>
</div>

app/views/matches/index.html.erb
<div class="match">
  <div class="container">
  <!-------------------- パンくずリスト ------------------------->
    <div class="row">
	  <div class="col-xs-3">
	    <ol class="bread_crumb_recruit breadcrumb">
		  <li><%= link_to "Home", posts_path, data: { "turbolinks" => false }, class: "glyphicon glyphicon-home" %></li>
		  <li class="active">Recruit</li>
		</ol>
	  </div>
	</div>
	<!------------------------------------------------------->
	<!---------------------- プロフィール ---------------------->
	<%= render "shared/simple_profile" %>
	<!------------------------------------------------------->
	<!------------------- フラッシュメッセージ ----------------->
	<%= render partial: "shared/flash" %>
	<!-------------------------------------------------------->
	<!-----------------  エラーメッセージ --------------------->
	<%= render "shared/error_messages", model: @match %>
	<!-------------------------------------------------------->
	<!------------------------ 投稿一覧 ------------------->
	<div class="margin-container row">
	  <div class="col-xs-offset-4 col-xs-4">
	    <h2 class="matches-title">- <%= fa_icon "search" %> Recruit Posts -</h2>
	  </div>
	</div>
	<!------------------- 　検索　------------------------------>
	<div class="row">
	  <div class="recruit-search box col-xs-offset-2 col-xs-8">
	    <%= search_form_for @search do |f| %>
		  <div class="search-btn radio-inline">
		    <%= f.radio_button :occupation_eq, true %>
			<%= fa_icon "users" %>
			<%= f.label :"Search students" %>
		  </div>
		  <div class="search-btn radio-inline">
		    <%= f.radio_button :occupation_eq, false %>
			<%= fa_icon "graduation-cap" %>
			<%= f.label :"Search teachers" %>
		  </div>
		  <div class="search-btn radio-inline">
		    <%= f.radio_button :occupation_eq, '', { checked: true } %>
			<%= f.label :"Both" %>
		  </div>
		  <div class="search-btn radio-inline">
		    <%= f.submit "Search", class: "btn btn-primary btn-xs" %>
		  </div>
		<% end %>
	  </div>
	</div>
	<!----------------------------------------------------------------->
	<div class="row">
	  <div class="col-xs-offset-2 col-xs-8">
	    <% @matches.each do |match| %>
		  <div class="box-simple">
		    <div class="row">
			  <div class="match-title-wrapper col-xs-offset-1 col-xs-10 ">
			    <strong class="match-index-title"><%= match.title %></strong>
			  </div>
			</div>
			<div class="row">
			  <div class="match-user-item">
			    <%= attachment_image_tag match.user, :image, fallback: "no-image.jpg", size:"100x100", id: "round-user-image" %>
				<%= link_to user_path(match.user.id) do %>
				  <p><%= match.user.name%></p>
				<% end %>
			  </div>
			</div>
			<div class="row">
		      <div class="col-xs-offset-1 col-xs-6 match-occupation">
			    <% if match.occupation == true %>
			      <p class="search-students"><%= fa_icon "users" %>Search Students</p>
				<% else %>
				  <p class="search-teachers"><%= fa_icon "graduation-cap" %>Search Teachers</p>
				<% end %>
			  </div>
			</div>
			<div class="row">
			  <div class="box-simple col-xs-offset-1 col-xs-10">
			    <p class="match-text"><%= match.text %></p>
				<div class="row">
				  <div class="col-xs-offset-9">
				    <%= fa_icon "calendar" %>
              		<%= create_time_with_country(current_user, match) %>
				  </div>
				</div>
			  </div>
			</div>
			<div class="row">
			  <div class="col-xs-offset-10">
			    <% if match.user.id == current_user.id %>
				  <%= link_to "Edit", edit_match_path(match), class: "btn btn-success" %>
				<% end %>
			  </div>
			</div>
		  </div>
		<% end %>
		<%= paginate @matches %>
	  </div>
	</div>
	<!----------------------------------------------------------->
	<!---------------------　投稿フォーム　------------------------->
	<div class="row">
	  <div class="col-xs-offset-3 col-xs-6">
	    <h2 class="match-form-title">- <%= fa_icon "pencil" %>Recruit Form -</h2>
	    <div class="box-simple">
		  <%= form_with model: @match, local: true do |f| %>
		    <div class="row">
			  <div class="match-margin col-xs-offset-1">
			    <%= f.radio_button :occupation, :true, checked: true %>
				<%= fa_icon "users" %>
				<%= f.label :occupation, "Search Students　" %>
				<%= f.radio_button :occupation, :false %>
				<%= fa_icon "graduation-cap" %>
				<%= f.label :occupation, "Search Teachers" %><br>
			  </div>
		    </div>
		    <div class="row">
			  <div class="col-xs-offset-1 col-xs-10">
			    <%= f.label :title, "Title"%>
				<%= f.text_field :title , class: "form-control"%><br>
				<%= f.label :title, "Text"%>
				<%= f.text_area :text, class: "form-control", rows: "8", cols: "40" %>
			  </div>
			</div>
			<div class="row">
			  <div class="match-margin col-xs-offset-8">
			    <%= f.submit "Post", class: "btn btn-primary"%>
			  </div>
			</div>
		  <% end %>
		</div>
	  </div>
	</div>
	<!------------------------------------------------------------------->
  </div>
</div>