config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions' }
  devise_scope :user do
    post "/users/guest_sign_in" => "users/sessions#new_guest"
  end
  root to: 'homes#top'
  get "home/welcome" => "homes#welcome"
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update index]
  resources :matches, only: %i[index update destroy create edit]
  resources :contacts, only: [:create]
  resources :messages, only: %i[create destroy]
  resources :rooms, only: %i[create show]
  resource :contacts, only: %i[new create]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :notifications, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :image

  validates :text, presence: true
  validates :text, length: { maximum: 141 }

  include Recent

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def create_notification_like!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
require 'net/http'
require 'uri'
require 'json'

class PostsController < ApplicationController
  include EnsureCorrectUser
  before_action :ensure_correct_post, only: %i[destroy edit update]

  def index
    @posts = Post.includes(:user).recent.page(params[:page]).per(8)
    @all_ranks = Post.includes(:user).find(Like.group(:post_id).order(Arel.sql('count(post_id) desc')).limit(3).pluck(:post_id))
    @slider_posts = Post.includes(:user).where.not(image_id: nil).limit(8)
    @tokyo_weather = get_weather('q=Tokyo,jp')
    @osaka_weather = get_weather('q=Osaka,jp')
    @cebu_weather = get_weather('q=Cebu,ph')
    @time_now_jp = Time.current.strftime('%Y/ %m/ %d/ %a')
    @time_now_ph = (Time.current - 1.hour).strftime('%Y/ %m/ %d/ %a')
  end

  def show
    @post = Post.find(params[:id])
    comments = @post.comments.includes(:user).recent
    @comments_by_third = comments[0..2]
    @comments_from_third = comments[3..(comments.count - 1)]
    @comments_count = comments.count
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = 'Newly posted '
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = 'Post has been updated'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:danger] = 'Post has been deleted'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:text, :image)
  end

  def get_weather(_code)
    weather_url = 'https://api.openweathermap.org/data/2.5/weather?' + _code + '&units=metric&cnt=3&appid='
    weather_url += ENV['OPEN_WEATHER_API_KEY']
    uri = URI.parse(weather_url)
    json = Net::HTTP.get(uri)
    result = JSON.parse(json)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="body">
  <div class="container">
<!--------------- パンくずリスト -------------------------->
    <div class="row">
	  <div class="col-xs-5">
	    <ol class="breadcrumb">
		  <li><%= link_to "Home", posts_path, data: { "turbolinks" => false }, class: "glyphicon glyphicon-home" %></li>
		  <li><%= link_to "My page", user_path(current_user) %></li>
		  <li class="active">Edit Post</li>
		</ol>
	  </div>
	</div>
<!------------------------------------------------------------>
<!---------------  プロフィール --------------------->
	<%= render "shared/simple_profile" %>
<!----------------------------------------------------->
<!--------------------------  エラーメッセージ  ---------------->
	<%= render "shared/error_messages", model: @post %>
<!-------------------------------------------------------->
	<div class="margin-container row">
	  <div class="col-xs-offset-2 col-xs-8">
	  <h2 class="edit-title">- <%= fa_icon "cog" %>  Edit Post -</h2>
	    <div class="box-simple">
		  <%= form_with model: @post, local: true do |f| %>
		  <div class="row">
		    <div class="post-edit-image col-xs-offset-1 col-xs-10">
			  <%= attachment_image_tag @post, :image, fallback: "no_image_post.jpg", class: "edit-post-preview"%>
			</div>
			<div class="row">
			  <div class="post-image-filed col-xs-offset-2 col-xs-5">
			    <%= f.attachment_field :image ,class: "upload-image", id: "edit-post-image"%>
			  </div>
			</div>
			<div class="post-image-filed col-xs-offset-1 col-xs-10">
			  <%= f.text_area :text , rows: "5", cols: "40", class: "form-control"%>
			</div>
			<div class="row">
			  <div class="update-btn col-xs-offset-7 col-xs-5">
			    <%= f.submit "Update", class: "btn btn-info" %>
				<%= link_to "Delete", post_path, method: :delete, data:{ confirm: "Are you sure you want to delete it?",cancel: "No", commit: "Yes" }, title: "Confirmation" , class: "btn btn-danger" %>
			  </div>
			</div>
		  </div>
		  <% end %>
		</div>
	  </div>
	</div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="body">
  <div class="post-index container">
 <!------------------- 新規投稿ボタン ------------------------->
    <%= link_to new_post_path, data: { "turbolinks" => false } do %>
	  <%= image_tag "logo-post.jpg", class: "logo-post" %>
	<% end %>
<!----------------------------------------------------------->
<!---------------------　フラッシュメッセージ ----------------------->
	<%= render partial: "shared/flash" %>
<!--------------------------------------------------------->
<!----------------------  パンくずリスト -------------------->
	<div class="row">
	  <div class="col-xs-2">
	    <ol class="breadcrumb">
		  <li class=" glyphicon glyphicon-home active ">Home</li>
		</ol>
	  </div>
	</div>
<!---------------------------------------------------------------->
<!-------------------------  プロフィール --------------------------->
	<%= render "shared/simple_profile" %>
<!-------------------------------------------------------------->
<!------------------------------- スライダー　------------------->
	<div class="bxslider">
	  <% @slider_posts.each do |post| %>
	    <%= link_to post_path(post) do %>
	      <%= attachment_image_tag post, :image, id: "slider-image" %>
	      <%= post.user.name %>
  		  <%= fa_icon "heart", style: "color=: red;"%>
		  <%= post.likes.count %>
	    <% end %>
      <% end %>
	</div>
<!--------------------------------------------------------->
<!---------------------- 時間　------------------------------->
    <div class="day">
	  <h2 class="day-country"><i>PHILIPINS</i></h2>
	  <h1><%= @time_now_ph %><p id="RealtimeClockAreaPH"></p></h1>
	  <h2 class="day-country"><i>JAPAN</i></h2>
	  <h1><%= @time_now_jp %><p id="RealtimeClockAreaJP"></p></h1>
	</div>
<!----------------------------------------------------------->
<!--------------------------- 天気　--------------------------->
	<hr>
	<div class="row weather-section">
	  <div class="col-xs-offset-3 col-xs-6">
	    <h3 class="weather-title">- Today`s Weather -</h3>
		<table class="table table-bordered table-responsive">
		  <thead>
		    <tr>
			  <th class="weather-thead col-xs-2"><strong><i>Cebu</i></strong></th>
			  <th class="weather-thead col-xs-2"><strong><i>Tokyo</i></strong></th>
			  <th class="weather-thead col-xs-2"><strong><i>Osaka</i></strong></th>
			</tr>
		  </thead>
		  <tbody>
		    <tr>
			  <td class="weather-icon"><%= image_tag "http://openweathermap.org/img/wn/" + @cebu_weather["weather"][0]["icon"] + "@2x.png" %>
			  </td>
			  <td class="weather-icon">
			    <%= image_tag "http://openweathermap.org/img/wn/" + @tokyo_weather["weather"][0]["icon"] + "@2x.png" %>
			  </td>
			  <td class="weather-icon">
			    <%= image_tag "http://openweathermap.org/img/wn/" + @osaka_weather["weather"][0]["icon"] + "@2x.png" %>
			  </td>
			</tr>
			<tr>
			  <td class="temp">
			    <%= @cebu_weather["main"]["temp"].floor(1) %>℃
			  </td>
			  <td class="temp">
			    <%= @tokyo_weather["main"]["temp"].floor(1) %>℃
			  </td>
			  <td class="temp">
			    <%= @osaka_weather["main"]["temp"].floor(1) %>℃
			  </td>
			</tr>
		  </tbody>
		</table>
	  </div>
	</div>
	<!------------------------------------------------------->
	<!------------------------ ランキング ------------------------>
	<hr>
	<div class="row">
	  <div class="col-xs-offset-2 col-xs-8">
	    <h2 class="rank-title">- <%= fa_icon "users" %> Ranking -</h2>
		  <% @all_ranks.each.with_index(1) do |post, i| %>
		<div class="post_content box-simple">
		  <h2  class="rank">
		    <% if i == 1 then %>
	          <%= image_tag 'gold.png', class: "crown" %>
			<% elsif i == 2 then %>
	          <%= image_tag 'silver.png', class: "crown" %>
			<% elsif i == 3 then %>
	          <%= image_tag 'bronz.png', class: "crown" %>
			<% end %>
		    <strong class="best">Best <%= i%></strong>
		  </h2>
		  <%= attachment_image_tag post, :image , id: "rank-post-image" %>
		  <div class="row">
		    <div class="post-index-user-image-rank">
		 	  <%= attachment_image_tag post.user, :image,  fallback: "no-image.jpg", size:"100x100", id: "round-user-image" %>
		      <%= link_to user_path(post.user.id) do %>
			    <p><strong><%= post.user.name %></strong></p>
			  <% end %>
		    </div>
		  </div>
		  <div class="row">
		    <div class="col">
		    <!------------------- いいね(非同期通信) ------------------>
			  <div id="likes_buttons_<%= post.id %>">
			    <%= render partial: "likes/like", locals: { post: post } %>
			  </div>
		    <!--------------------------------------------------------->
			</div>
		  </div>
		  <div class="row">
		    <div class="box-simple post-index-post-text col-xs-offset-1 col-xs-10">
			  <strong><%= post.text %></strong>
		    </div>
		  </div>
		  <div class="row">
		    <div class="col-xs-offset-7 col-xs-6">
		      <%= fa_icon "comment-o" %>
			  <%= post.comments.count %>
		      <%= fa_icon "calendar" %>
		      <%= create_time_with_country(current_user, post) %>
		    </div>
		  </div>
		  <div class="row">
		    <div class="post-index-more col-xs-offset-9 col-xs-2">
			  <%= link_to "more",post_path(post), class: "btn btn-info" %>
		    </div>
		  </div>
	    </div>
		<% end %>
	  </div>
    </div>
<!--------------------- ランキングここまで  ------------------------>
<!--------------------------　投稿一覧　----------------------------->
	<hr>
	<div class="margin-container row">
	  <div class="col-xs-offset-3 col-xs-6">
	    <h2 class="post-index-title">- <%= fa_icon "globe" %> Latest posts -</h2>
		<% @posts.each do |post| %>
		  <div class="box-simple">
		    <div class="row">
			  <div class="col-xs-12">
		        <%= attachment_image_tag post, :image, id: "post-index-image"%>
			  </div>
			</div>
		    <div class="row">
			  <div class="post-index-user-image">
			    <%= attachment_image_tag post.user, :image, fallback: "no-image.jpg", size:"60x60", id: "round-user-image" %>
				<%= link_to user_path(post.user.id) do %>
				  <p><strong><%= post.user.name %></strong></p>
				<% end %>
			  </div>
			</div>
			<div class="row">
			  <div class="col">
		<!-------------------------- いいね(非同期通信) ------------------------>
			    <div id="likes_buttons_<%= post.id %>">
				  <%= render partial: "likes/like", locals: { post: post } %>
				</div>
	   <!------------------------------------------------------------------->
			  </div>
			</div>
			<div class="row">
			  <div class="box-simple post-index-post-text col-xs-offset-1 col-xs-10">
			    <strong><%= post.text %></strong>
			  </div>
			</div>
		    <div class="row">
			  <div class="col-xs-offset-7 col-xs-8">
			    <%= fa_icon "comment-o" %>
				<%= post.comments.count %>
		        <%= fa_icon "calendar" %>
			    <%= create_time_with_country(current_user, post) %>
			  </div>
			</div>
			<div class="row">
			  <div class="post-index-more col-xs-offset-9 col-xs-2">
			    <%= link_to "more", post_path(post), class: "btn btn-info" %>
			  </div>
			</div>
		  </div>
	    <% end %>
	    <div class="col-xs-offset-4">
	      <%= paginate @posts %>
	    </div>
	  </div>
    </div>
    <!------------------ 投稿一覧ここまで　------------------------------------->
  </div>
</div>

app/views/posts/new.html.erb
<div class="body">
  <div class="container">
    <div class="row">
	  <div class="col-xs-3">
	<!---------------- パンくずリスト ----------------------------->
	    <ol class="breadcrumb">
		  <li><%= link_to "Home", posts_path, data: { "turbolinks" => false }, class: "glyphicon glyphicon-home"%></li>
		  <li class="active">New Post</li>
		</ol>
	<!------------------------------------------------------------->
	<!--------------- プロフィール --------------------------------->
		<%= render "shared/simple_profile" %>
	<!---------------------------------------------------------->
	<!---------------  エラーメッセージ ----------------------------->
		<%= render "shared/error_messages", model: @post %>
	<!--------------------------------------------------------->
	  </div>
	</div>
	<div class="row">
	  <div class="col-xs-offset-2 col-xs-8">
	    <h2 class="new-post-title">- <%= fa_icon "wrench" %> New Post -</h2>
		<%= form_with model: @post, local: true do |f| %>
		  <div class="box-simple">
		    <div class="row">
			  <div class="upload-image col-xs-offset-1 col-xs-10">
			    <%= attachment_image_tag @post, :image, fallback: "no_image_post.jpg", class: "post-preview"%>
			  </div>
			</div>
		  <div class="row">
		    <div class="image-field col-xs-offset-2">
			  <%= f.attachment_field :image, id: "new-post-image" %>
			</div>
		  </div>
		  <div class="row">
		    <div class="col-xs-offset-1 col-xs-10">
			  <%= f.text_area :text, :placeholder => "　What are you doing now?", rows: "5", cols: "50", class: "form-control" %>
			 </div>
		  </div>
		  <div class="row">
		    <div class="col-xs-offset-9">
			  <%= f.submit "Post", class: "btn-post btn btn-info" %>
			</div>
		  </div>
		</div>
		<% end %>
	  </div>
	</div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="body">
  <div class="container">
  <!---------------------  パンくずリスト  --------------------->
    <div class="row">
	  <div class="col-xs-4">
	    <ol class="breadcrumb">
		  <li><%= link_to "Home", posts_path, data: { "turbolinks" => false }, class: "glyphicon glyphicon-home" %></li>
		  <li class="active">Post</li>
		</ol>
	  </div>
	</div>
  <!------------------------------------------------------------->
  <!--------------------- プロフィール --------------------------->
	<%= render "shared/simple_profile" %>
	<!--------------------------------------------------------->
	<!-------------------------- フラッシュメッセージ ------------>
	<div id="flash_area">
	  <%= render partial: "shared/flash" %>
	</div>
	<!-------------------------------------------------------->
	<!--------------- エラーメッセージ  ------------------------>
	<div id="error_area"></div>
	<!--------------------------------------------------------->
	<!--------------- 投稿詳細　--------------------------------->
	<div class="margin-container row">
	  <div class="col-xs-offset-2 col-xs-8">
	    <h2 class="post-show-title">-  <%= @post.user.name %>`s Post -</h2>
	    <div class="box-simple">
		  <div class="post-show-image">
		    <%= attachment_image_tag @post, :image %>
		  </div>
		  <div class="row">
		    <div class="post-show-user-image col-xs-offset-1 col-xs-2">
		      <%= attachment_image_tag @post.user, :image, fallback: "no-image.jpg", size:"60x60", id: "round-user-image" %>
		    </div>
	      </div>
		  <div class="row">
		    <div class="post-show-name col-xs-2">
		      <%= link_to user_path(@post.user_id) do %>
			    <%= @post.user.name %>
			  <% end %>
		    </div>
		  </div>
	<!-------------------------- 　いいね(非同期通信)　------------------------>
		  <div class="row">
		    <div id="likes_buttons_<%= @post.id %>">
		　    <%= render partial: "likes/like", locals: { post: @post } %>
		    </div>
		  </div>
	<!-------------------------------------------------------------------->
		  <div class="row">
	        <div class="box-simple post-show-text col-xs-offset-1 col-xs-10">
		      <strong><%= @post.text %></strong>
		    </div>
		  </div>
	      <div class="row">
	        <div class="col-xs-offset-8">
		      <%= fa_icon "calendar" %>
		      <%= create_time_with_country(current_user, @post) %>
		    </div>
		  </div>
          <div class="row">
            <div class="post-show-edit-btn col-xs-offset-9">
              <% if @post.user_id == current_user.id %>
      		    <%= link_to "Edit", edit_post_path(@post), data: { "turbolinks" => false }, class: "btn btn-primary" %>
      		  <% end %>
            </div>
      	  </div>
        </div>
	  </div>
	</div>
	<!---------------------------- 　投稿詳細　ここまで　-------------->
	<!------------------------------ コメント一覧 --------------------->
	<div id="comment_area">
	  <%= render partial: "comments/comment", locals: { comments_by_third: @comments_by_third, comments_from_third: @comments_from_third, count: @comments_count, post: @post } %>
	</div>
	<!--------------------------------------------------------->
	<!--------------------- コメントフォーム(非同期通信) ----------------->
	<div id="comment-form">
	  <%= render partial: "comments/comment_form", locals: { comment: @comment, post: @post } %>
	</div>
	<!------------------------------------------------------------------->
  </div>
</div>