config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  devise_for :users, :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions' }
  devise_scope :user do
    post "/users/guest_sign_in" => "users/sessions#new_guest"
  end
  root to: 'homes#top'
  get "home/welcome" => "homes#welcome"
  resources :posts do
    resource :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :users, only: %i[show edit update index]
  resources :matches, only: %i[index update destroy create edit]
  resources :contacts, only: [:create]
  resources :messages, only: %i[create destroy]
  resources :rooms, only: %i[create show]
  resource :contacts, only: %i[new create]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :notifications, dependent: :destroy
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

  include Recent

end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user

  validates :text, presence: true
  validates :title, presence: true
  validates :occupation, inclusion: { in: [true, false] }

  include Recent

end

app/models/message.rb
class Message < ApplicationRecord
  has_many :notifications, dependent: :destroy
  belongs_to :user
  belongs_to :room

  validates :message, presence: true

  include Recent

  def create_notification_message!(current_user, message_id, visited_id)
    notification = current_user.active_notifications.new(
      message_id: message_id,
      visited_id: visited_id,
      action: 'message'
    )
    notification.save if notification.valid?
  end
end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :message, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true

  include Recent

  def self.destroy_read_notifications
    notifications = Notification.where(checked: true)
    notifications.delete_all
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :notifications, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :image

  validates :text, presence: true
  validates :text, length: { maximum: 141 }

  include Recent

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  def create_notification_like!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  belongs_to :user
  belongs_to :guest, class_name: 'User', foreign_key: 'guest_id', optional: true

  include Recent

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable, :trackable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :matches, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :email, presence: true
  validates :country, inclusion: { in: [true, false] }
  VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }, on: :create

  def like_sum
    sum = 0
    posts.each do |post|
      sum += post.likes.count
    end
    sum
  end

  def self.guest
    find_or_create_by(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "GUEST"
      user.country = false
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Segurado!</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="header">
    <!--------------　ロゴ　------------------>
    <div class="header-logo">
      <%= image_tag 'logo.jpg', alt: "[Logo]whale shark" %>
    </div>
    <!-------------------------------------------->
    <nav>
      <ul>
        <% if user_signed_in? %>
          <div class="nav-list">
            <%= fa_icon "home" %>
            <%= link_to "Home", posts_path , data: { "turbolinks" => false } %>
          </div>
          <div class="nav-list">
            <%= fa_icon "user-circle-o" %>
            <%= link_to "My page",user_path(current_user)%>
          </div>
          <div class="nav-list">
            <%= fa_icon "users" %>
            <%= link_to "Users", users_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "handshake-o" %>
            <%= link_to "Recruit", matches_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "paper-plane-o" %>
            <%= link_to "Contact", new_contacts_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "sign-out" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </div>
        <% else %>
          <div class="nav-list">
            <%= fa_icon "home" %>
            <%= link_to "Top", root_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "user-plus"%>
            <%= link_to "Sign up", new_user_registration_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "sign-in"%>
            <%= link_to "Log in", new_user_session_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "paper-plane-o" %>
            <%= link_to "Contact", new_contacts_path %>
          </div>
          <div class="nav-list guest-login">
            <%= fa_icon "users" %>
            <%= link_to "GUEST LOGIN", users_guest_sign_in_path, method: :post, data: { "turbolinks" => false } %>
          </div>
        <% end %>
      </ul>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
  <footer>
    <p id="page-top"><a href="#"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span></a></p>
      <!----------------------- 　ロゴ　------------------------>
    <div class="row">
      <div class="footer-logo">
        <%= link_to posts_path, data: { "turbolinks" => false } do %>
          <%= image_tag 'logo2.jpg', alt: "[Logo]title" %>
        <% end %>
      </div>
    </div>
    <!------------------------------------------------------------------>
  </footer>
</html>

app/views/layouts/homes.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Segurado!</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
  <footer>
    <p id="page-top"><a href="#"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span></a></p>
      <!------------------------　ロゴ　------------->
    <div class="row">
      <div class="footer-logo">
        <%= link_to posts_path, data: { "turbolinks" => false } do %>
          <%= image_tag 'logo2.jpg', alt: "[Logo]title" %>
        <% end %>
      </div>
    </div>
    <!---------------------------------------------->
  </footer>
</html>

app/views/layouts/matches.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Segurado!Rectuit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="header_recruit">
    <!----------------------　ロゴ -------------------->
    <div class="header-logo">
        <%= image_tag 'logo.jpg', alt: "[Logo]whale shark" %>
    </div>
    <!---------------------------------------------------->
    <nav>
      <ul>
        <% if user_signed_in? %>
          <div class="nav-list">
            <%= fa_icon "home" %>
            <%= link_to "Home", posts_path, data: { "turbolinks" => false } %>
          </div>
          <div class="nav-list">
            <%= fa_icon "user-circle-o" %>
            <%= link_to "My page",user_path(current_user)%>
          </div>
          <div class="nav-list">
            <%= fa_icon "users" %>
            <%= link_to "Users", users_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "handshake-o" %>
            <%= link_to "Recruit", matches_path %>
          </div>
          <div class="nav-list">
              <%= fa_icon "paper-plane-o" %>
              <%= link_to "Contact", new_contacts_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "sign-out" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          </div>
        <% else %>
          <div class="nav-list">
            <%= fa_icon "home" %>
            <%= link_to "Top", root_path %>
          </div>
          <div class="nav-list">
            <%= fa_icon "user-plus"%>
            <%= link_to "Sign up", new_user_registration_path %>
          </div>
          <div class="nav-list">
              <%= fa_icon "sign-in"%>
              <%= link_to "Log in", new_user_session_path %>
          </div>
          <div class="nav-list">
              <%= fa_icon "paper-plane-o" %>
              <%= link_to "Contact", new_contacts_path %>
          </div>
        <% end %>
      </ul>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
  <footer>
    <p id="page-top"><a href="#"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span></a></p>
      <!----------------------　ロゴ ----------------------->
    <div class="row">
      <div class="footer-logo">
        <%= link_to posts_path, data: { "turbolinks" => false } do %>
          <%= image_tag 'logo2.jpg', alt: "[Logo]title" %>
        <% end %>
      </div>
    </div>
    <!------------------------------------------------------>
  </footer>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <% model.errors.full_messages.each do |message| %>
      <%= message %>
	  <button type="button" class="close" data-dismiss="alert">　&times;</button><br>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
	<button type="button" class="close" data-dismiss="alert">　&times;</button>
  </div>
<% end %>

app/views/shared/_notifications.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<div class="row">
  <div class="notification-item col-xs-offset-1 col-xs-11">
    <div class="notification-section">
	  <%= link_to user_path(notification.visitor) do %>
	    <%= attachment_image_tag notification.visitor, :image, fallback: "no-image.jpg", size: "40x40" %>
		<p class="notification-name"><strong><%= visitor.name %></strong></p>
	  <% end %>
	</div>
	<div class="aciton-section">
	  <% case notification.action %>
	  <% when "like" then %>
	    <%= fa_icon "heart", style: "color=: red;" %>
		  <strong>LIKED</strong>
		<%= link_to "Your post", notification.post %>
	  <% when "comment" then %>
	    <%= fa_icon "comment-o" %>
		<% if notification.comment.user_id == visited.id %>
		  <%= link_to "your post", notification.post %>
		<% else %>
		  <strong>COMMENTED</strong>
		  <%= link_to post_path(notification.post) do %>
		    Your post
		    <% Comment.find_by(id: notification.comment_id) %>
		  <% end %>
		<% end %>
	  <% when "message" then %>
	    <% if notification.message.user_id == visitor.id %>
		  <%= fa_icon "envelope-o" %>
		  <strong>SENT A MESSAGE</strong>
		<% end %>
	  <% end %>
	  <div class="notification-time col-xs-7">
	    <%= time_ago_in_words(notification.created_at).upcase %>
	  </div>
	</div>
  </div>
</div>

app/views/shared/_simple_profile.html.erb
<div class="container">
  <% if user_signed_in? %>
    <div class="user-box">
      <%= attachment_image_tag current_user, :image, fallback: "no-image.jpg", size:"60x60", id: "round-user-image" %>
	  <p>Welcome!</p>
	  <%= link_to current_user.name, user_path(current_user), class: "user-name" %>
	  <%= link_to user_path(current_user) do %>
	    <div>
	      <%= fa_icon "bell-o"%>
		</div>
		<% if exist_unchecked_notifications %>
		  <i class="fa fa-circle notification-circle"></i>
		<% end %>
	  <% end %>
	</div>
  <% end %>
</div>